import type { AsignaturaMalla, AñoData } from "./types";

export const MALLA_ASIGNATURAS: AsignaturaMalla[] = [
  // ── AÑO 1: SEMESTRE I ──
  {
    id: "geom-plana",
    nombre: "Geometría Plana",
    codigo: "MAT-101",
    semestre: 1,
    semestreRomano: "I",
    año: 1,
    creditos: 6,
    area: "disciplinar",
    descripcion: "Estudio axiomático euclidiano, construcciones geométricas, congruencia y semejanza de figuras.",
  },
  {
    id: "alg-elemental",
    nombre: "Álgebra Elemental",
    codigo: "MAT-102",
    semestre: 1,
    semestreRomano: "I",
    año: 1,
    creditos: 6,
    area: "disciplinar",
    descripcion: "Fundamentos algebraicos, teoría de conjuntos, relaciones, polinomios y factorización.",
  },
  {
    id: "taller-res-prob",
    nombre: "Taller de Integración en Resolución de Problemas",
    codigo: "DID-101",
    semestre: 1,
    semestreRomano: "I",
    año: 1,
    creditos: 4,
    area: "didactica",
    descripcion: "Estrategias de resolución heurística según Polya y desarrollo de pensamiento matemático.",
  },
  {
    id: "psic-educacional",
    nombre: "Psicología Educacional",
    codigo: "PED-101",
    semestre: 1,
    semestreRomano: "I",
    año: 1,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Desarrollo cognitivo, teorías del aprendizaje aplicadas a la adolescencia y contexto escolar.",
  },
  {
    id: "tec-aprendizaje",
    nombre: "Tecnologías para el Aprendizaje",
    codigo: "TIC-101",
    semestre: 1,
    semestreRomano: "I",
    año: 1,
    creditos: 3,
    area: "general",
    descripcion: "Herramientas digitales, entornos virtuales de aprendizaje y software educativo.",
  },
  {
    id: "comp-comunicativas",
    nombre: "Competencias Comunicativas (FIP)",
    codigo: "FIP-101",
    semestre: 1,
    semestreRomano: "I",
    año: 1,
    creditos: 3,
    area: "general",
    descripcion: "Habilidades de comunicación oral y escrita esenciales para la labor pedagógica docente.",
  },
  {
    id: "ingles-com-1",
    nombre: "Inglés Comunicacional I (FIP)",
    codigo: "ING-101",
    semestre: 1,
    semestreRomano: "I",
    año: 1,
    creditos: 3,
    area: "general",
    descripcion: "Desarrollo de competencias lingüísticas básicas en idioma inglés (Nivel A1-A2).",
  },

  // ── AÑO 1: SEMESTRE II ──
  {
    id: "geom-espacio",
    nombre: "Geometría del Espacio",
    codigo: "MAT-103",
    semestre: 2,
    semestreRomano: "II",
    año: 1,
    creditos: 5,
    area: "disciplinar",
    prerrequisitos: ["Geometría Plana"],
    descripcion: "Planos, rectas y poliedros tridimensionales, áreas de superficie y volúmenes.",
  },
  {
    id: "alg-trigo",
    nombre: "Álgebra y Trigonometría",
    codigo: "MAT-104",
    semestre: 2,
    semestreRomano: "II",
    año: 1,
    creditos: 6,
    area: "disciplinar",
    prerrequisitos: ["Álgebra Elemental"],
    descripcion: "Funciones trigonométricas, identidades, ecuaciones y números complejos.",
  },
  {
    id: "didactica-fundamental",
    nombre: "Didáctica Fundamental de la Matemática",
    codigo: "DID-102",
    semestre: 2,
    semestreRomano: "II",
    año: 1,
    creditos: 5,
    area: "didactica",
    prerrequisitos: ["Taller de Integración en Resolución de Problemas"],
    descripcion: "Transposición didáctica de Chevallard, situaciones didácticas de Brousseau y teoría de campos conceptuales.",
  },
  {
    id: "soc-genero",
    nombre: "Sociología Educacional con Enfoque de Género",
    codigo: "PED-102",
    semestre: 2,
    semestreRomano: "II",
    año: 1,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Análisis sociológico del sistema escolar chileno y perspectiva inclusiva de género.",
  },
  {
    id: "filosofia-educacional",
    nombre: "Filosofía Educacional",
    codigo: "PED-103",
    semestre: 2,
    semestreRomano: "II",
    año: 1,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Epistemología y corrientes filosóficas fundamentales que sustentan el quehacer pedagógico.",
  },
  {
    id: "ingles-com-2",
    nombre: "Inglés Comunicacional II (FIP)",
    codigo: "ING-102",
    semestre: 2,
    semestreRomano: "II",
    año: 1,
    creditos: 3,
    area: "general",
    prerrequisitos: ["Inglés Comunicacional I (FIP)"],
    descripcion: "Consolidación de estructuras gramaticales y comprensión lectora en inglés (Nivel A2).",
  },
  {
    id: "fi-oferta-1",
    nombre: "Formación Integral Oferta Institucional",
    codigo: "FIO-101",
    semestre: 2,
    semestreRomano: "II",
    año: 1,
    creditos: 2,
    area: "general",
    descripcion: "Asignatura electiva institucional de artes, humanidades o responsabilidad social universitaria.",
  },

  // ── AÑO 2: SEMESTRE III ──
  {
    id: "geom-analitica",
    nombre: "Geometría Analítica",
    codigo: "MAT-201",
    semestre: 3,
    semestreRomano: "III",
    año: 2,
    creditos: 5,
    area: "disciplinar",
    prerrequisitos: ["Geometría del Espacio", "Álgebra y Trigonometría"],
    descripcion: "Lugares geométricos, rectas, cónicas (circunferencia, elipse, parábola, hipérbola) y transformaciones.",
  },
  {
    id: "calc-diferencial",
    nombre: "Cálculo Diferencial",
    codigo: "MAT-202",
    semestre: 3,
    semestreRomano: "III",
    año: 2,
    creditos: 6,
    area: "disciplinar",
    prerrequisitos: ["Álgebra y Trigonometría"],
    descripcion: "Límites, continuidad, derivada de funciones en una variable y optimización.",
  },
  {
    id: "aritmetica",
    nombre: "Aritmética",
    codigo: "MAT-203",
    semestre: 3,
    semestreRomano: "III",
    año: 2,
    creditos: 5,
    area: "disciplinar",
    descripcion: "Propiedades de los números enteros, divisibilidad, números primos, congruencias y teorema fundamental.",
  },
  {
    id: "did-sistemas-numericos",
    nombre: "Didáctica de los Sistemas Numéricos",
    codigo: "DID-201",
    semestre: 3,
    semestreRomano: "III",
    año: 2,
    creditos: 5,
    area: "didactica",
    prerrequisitos: ["Didáctica Fundamental de la Matemática"],
    descripcion: "Didáctica para la enseñanza de los conjuntos numéricos N, Z, Q y R en educación secundaria.",
  },
  {
    id: "sociedad-cultura-educacion",
    nombre: "Sociedad, Cultura y Educación",
    codigo: "PED-201",
    semestre: 3,
    semestreRomano: "III",
    año: 2,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Dinámicas culturales y transformaciones sociales que impactan a la escuela contemporánea.",
  },
  {
    id: "ingles-com-3",
    nombre: "Inglés Comunicacional III (FIP)",
    codigo: "ING-201",
    semestre: 3,
    semestreRomano: "III",
    año: 2,
    creditos: 3,
    area: "general",
    prerrequisitos: ["Inglés Comunicacional II (FIP)"],
    descripcion: "Producción de textos y comprensión auditiva intermedia en inglés (Nivel B1 inicial).",
  },

  // ── AÑO 2: SEMESTRE IV ──
  {
    id: "did-geometria",
    nombre: "Didáctica de la Geometría",
    codigo: "DID-202",
    semestre: 4,
    semestreRomano: "IV",
    año: 2,
    creditos: 5,
    area: "didactica",
    prerrequisitos: ["Geometría Analítica", "Didáctica Fundamental de la Matemática"],
    descripcion: "Modelo de Van Hiele, diseño de secuencias de enseñanza y uso de GeoGebra en el aula.",
  },
  {
    id: "calc-integral",
    nombre: "Cálculo Integral",
    codigo: "MAT-204",
    semestre: 4,
    semestreRomano: "IV",
    año: 2,
    creditos: 6,
    area: "disciplinar",
    prerrequisitos: ["Cálculo Diferencial"],
    descripcion: "Integrales definidas e indefinidas, teorema fundamental del cálculo, técnicas y aplicaciones.",
  },
  {
    id: "alg-lineal",
    nombre: "Álgebra Lineal",
    codigo: "MAT-205",
    semestre: 4,
    semestreRomano: "IV",
    año: 2,
    creditos: 6,
    area: "disciplinar",
    descripcion: "Espacios vectoriales, matrices, determinantes, sistemas de ecuaciones lineales y transformaciones lineales.",
  },
  {
    id: "curriculum-educacional",
    nombre: "Currículum Educacional",
    codigo: "PED-202",
    semestre: 4,
    semestreRomano: "IV",
    año: 2,
    creditos: 4,
    area: "pedagogica",
    idAsignaturaDb: 1,
    descripcion: "Bases curriculares chilenas de matemática, planificación por competencias y alineamiento constructivo.",
  },
  {
    id: "ingles-com-4",
    nombre: "Inglés Comunicacional IV (FIP)",
    codigo: "ING-202",
    semestre: 4,
    semestreRomano: "IV",
    año: 2,
    creditos: 3,
    area: "general",
    prerrequisitos: ["Inglés Comunicacional III (FIP)"],
    descripcion: "Fluidez oral y comprensión de textos pedagógicos en inglés (Nivel B1 consolidado).",
  },
  {
    id: "aprox-sistema-escolar",
    nombre: "Aproximación al Sistema Escolar",
    codigo: "PRA-201",
    semestre: 4,
    semestreRomano: "IV",
    año: 2,
    creditos: 4,
    area: "practica",
    descripcion: "Primera inmersión de observación participante en establecimientos educacionales de la región.",
  },

  // ── AÑO 3: SEMESTRE V ──
  {
    id: "est-prob",
    nombre: "Estadísticas y Probabilidades",
    codigo: "MAT-301",
    semestre: 5,
    semestreRomano: "V",
    año: 3,
    creditos: 6,
    area: "disciplinar",
    descripcion: "Estadística descriptiva, variables aleatorias discretas y continuas, distribuciones y modelos probabilísticos.",
  },
  {
    id: "calc-varias-var",
    nombre: "Cálculo en Varias Variables",
    codigo: "MAT-302",
    semestre: 5,
    semestreRomano: "V",
    año: 3,
    creditos: 6,
    area: "disciplinar",
    prerrequisitos: ["Cálculo Integral"],
    descripcion: "Cálculo multivariable, derivadas parciales, gradiente, integrales múltiples y análisis vectorial.",
  },
  {
    id: "razonamiento-mat",
    nombre: "Razonamiento en Matemática",
    codigo: "MAT-303",
    semestre: 5,
    semestreRomano: "V",
    año: 3,
    creditos: 5,
    area: "disciplinar",
    descripcion: "Lógica proposicional formal, métodos de demostración directa, inducción y reducción al absurdo.",
  },
  {
    id: "errores-obstaculos-mat",
    nombre: "Errores y Obstáculos del Aprendizaje en Matemática",
    codigo: "DID-301",
    semestre: 5,
    semestreRomano: "V",
    año: 3,
    creditos: 4,
    area: "didactica",
    descripcion: "Identificación y tratamiento de obstáculos epistemológicos, ontogénicos y didácticos.",
  },
  {
    id: "didactica-general",
    nombre: "Didáctica General",
    codigo: "PED-301",
    semestre: 5,
    semestreRomano: "V",
    año: 3,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Principios pedagógicos de la enseñanza, mediación docente y estrategias metodológicas.",
  },
  {
    id: "ambientes-aprendizaje",
    nombre: "Ambientes de Aprendizaje",
    codigo: "PED-302",
    semestre: 5,
    semestreRomano: "V",
    año: 3,
    creditos: 3,
    area: "pedagogica",
    idAsignaturaDb: 2,
    descripcion: "Diseño de espacios formativos estimulantes, clima escolar propicio y bienestar estudiantil.",
  },

  // ── AÑO 3: SEMESTRE VI ──
  {
    id: "inf-estadistica",
    nombre: "Inferencia Estadística",
    codigo: "MAT-304",
    semestre: 6,
    semestreRomano: "VI",
    año: 3,
    creditos: 6,
    area: "disciplinar",
    prerrequisitos: ["Estadísticas y Probabilidades"],
    descripcion: "Estimación puntual y por intervalos, pruebas de hipótesis paramétricas y no paramétricas.",
  },
  {
    id: "est-algebraicas",
    nombre: "Estructuras Algebraicas",
    codigo: "MAT-305",
    semestre: 6,
    semestreRomano: "VI",
    año: 3,
    creditos: 6,
    area: "disciplinar",
    prerrequisitos: ["Álgebra Lineal"],
    descripcion: "Grupos, anillos, cuerpos, homomorfismos y aplicaciones a la matemática moderna.",
  },
  {
    id: "did-algebra-funciones",
    nombre: "Didáctica del Álgebra y de las Funciones",
    codigo: "DID-302",
    semestre: 6,
    semestreRomano: "VI",
    año: 3,
    creditos: 5,
    area: "didactica",
    descripcion: "Transición del pensamiento aritmético al algebraico y visualización de funciones.",
  },
  {
    id: "eval-aprendizaje",
    nombre: "Evaluación para el Aprendizaje",
    codigo: "PED-303",
    semestre: 6,
    semestreRomano: "VI",
    año: 3,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Diseño de instrumentos auténticos, rúbricas de evaluación, retroalimentación y decreto 67.",
  },
  {
    id: "gestion-liderazgo",
    nombre: "Gestión Educacional y Liderazgo Escolar",
    codigo: "PED-304",
    semestre: 6,
    semestreRomano: "VI",
    año: 3,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Liderazgo directivo y pedagógico, gestión de proyectos institucionales y trabajo en equipo.",
  },
  {
    id: "trabajo-colaborativo-aula",
    nombre: "Trabajo Colaborativo en Aula",
    codigo: "PRA-301",
    semestre: 6,
    semestreRomano: "VI",
    año: 3,
    creditos: 4,
    area: "practica",
    idAsignaturaDb: 3,
    descripcion: "Práctica intermedia de co-docencia y diseño colaborativo de unidades de aprendizaje.",
  },

  // ── AÑO 4: SEMESTRE VII ──
  {
    id: "did-estadistica",
    nombre: "Didáctica de la Estadística",
    codigo: "DID-401",
    semestre: 7,
    semestreRomano: "VII",
    año: 4,
    creditos: 5,
    area: "didactica",
    prerrequisitos: ["Inferencia Estadística"],
    descripcion: "Alfabetización estadística, razonamiento probabilístico y análisis de datos en enseñanza media.",
  },
  {
    id: "ecuaciones-dif",
    nombre: "Ecuaciones Diferenciales",
    codigo: "MAT-401",
    semestre: 7,
    semestreRomano: "VII",
    año: 4,
    creditos: 6,
    area: "disciplinar",
    prerrequisitos: ["Cálculo en Varias Variables"],
    descripcion: "Ecuaciones diferenciales ordinarias de primer y segundo orden, transformada de Laplace y modelos aplicados.",
  },
  {
    id: "historia-epist-mat",
    nombre: "Historia y Epistemología de la Matemática",
    codigo: "MAT-402",
    semestre: 7,
    semestreRomano: "VII",
    año: 4,
    creditos: 4,
    area: "disciplinar",
    descripcion: "Evolución histórica de los conceptos matemáticos fundamentales y su impacto en la enseñanza.",
  },
  {
    id: "tec-ensenanza-mat",
    nombre: "Tecnología y Enseñanza de la Matemática",
    codigo: "DID-402",
    semestre: 7,
    semestreRomano: "VII",
    año: 4,
    creditos: 4,
    area: "didactica",
    descripcion: "Software dinámico avanzado, calculadoras gráficas, programación y simulaciones aplicadas al aula.",
  },
  {
    id: "investigacion-educacional",
    nombre: "Investigación Educacional",
    codigo: "PED-401",
    semestre: 7,
    semestreRomano: "VII",
    año: 4,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Metodologías cuantitativas y cualitativas aplicadas a problemas de investigación pedagógica.",
  },
  {
    id: "fi-oferta-2",
    nombre: "Formación Integral Oferta Institucional",
    codigo: "FIO-401",
    semestre: 7,
    semestreRomano: "VII",
    año: 4,
    creditos: 2,
    area: "general",
    descripcion: "Segundo electivo de profundización en desarrollo personal, ciudadanía o innovación social.",
  },
  {
    id: "investigacion-aula",
    nombre: "Investigación en Aula",
    codigo: "PRA-401",
    semestre: 7,
    semestreRomano: "VII",
    año: 4,
    creditos: 4,
    area: "practica",
    idAsignaturaDb: 4,
    descripcion: "Diseño de proyectos de investigación-acción para optimizar aprendizajes reales en el colegio.",
  },

  // ── AÑO 4: SEMESTRE VIII ──
  {
    id: "electivo-1",
    nombre: "Electivo I",
    codigo: "ELE-401",
    semestre: 8,
    semestreRomano: "VIII",
    año: 4,
    creditos: 4,
    area: "general",
    descripcion: "Asignatura electiva de profundización disciplinar o didáctica.",
  },
  {
    id: "electivo-2",
    nombre: "Electivo II",
    codigo: "ELE-402",
    semestre: 8,
    semestreRomano: "VIII",
    año: 4,
    creditos: 4,
    area: "general",
    descripcion: "Asignatura electiva de profundización pedagógica o tecnológica.",
  },
  {
    id: "lab-didactica-mat",
    nombre: "Laboratorio de la Didáctica Matemática",
    codigo: "DID-403",
    semestre: 8,
    semestreRomano: "VIII",
    año: 4,
    creditos: 5,
    area: "didactica",
    descripcion: "Experimentación con material concreto, modelación y micro-enseñanzas grabadas en video.",
  },
  {
    id: "proyecto-grado",
    nombre: "Proyecto de Grado",
    codigo: "PRA-402",
    semestre: 8,
    semestreRomano: "VIII",
    año: 4,
    creditos: 6,
    area: "practica",
    descripcion: "Formulación y anteproyecto de tesis de licenciatura en educación matemática.",
  },
  {
    id: "orientacion-convivencia",
    nombre: "Orientación Educacional y Convivencia Escolar",
    codigo: "PED-402",
    semestre: 8,
    semestreRomano: "VIII",
    año: 4,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Rol del profesor jefe, mediación de conflictos escolares y desarrollo socioemocional.",
  },
  {
    id: "inclusion-nee",
    nombre: "Inclusión Educacional y Necesidades Especiales",
    codigo: "PED-403",
    semestre: 8,
    semestreRomano: "VIII",
    año: 4,
    creditos: 4,
    area: "pedagogica",
    descripcion: "Diseño Universal para el Aprendizaje (DUA) y adecuaciones curriculares individuales.",
  },
  {
    id: "practica-pedagogica",
    nombre: "Práctica Pedagógica",
    codigo: "PRA-403",
    semestre: 8,
    semestreRomano: "VIII",
    año: 4,
    creditos: 6,
    area: "practica",
    idAsignaturaDb: 5,
    descripcion: "Práctica intensiva en aula escolar: planificación, docencia directa y evaluación formativa.",
  },

  // ── AÑO 5: SEMESTRE IX ──
  {
    id: "fi-extraprogramatica",
    nombre: "Formación Integral en Actividades Extraprogramática",
    codigo: "FIO-501",
    semestre: 9,
    semestreRomano: "IX",
    año: 5,
    creditos: 3,
    area: "general",
    descripcion: "Reconocimiento de participación en actividades culturales, deportivas o de voluntariado UBB.",
  },
  {
    id: "titulacion-1",
    nombre: "Actividad de Titulación I",
    codigo: "TIT-501",
    semestre: 9,
    semestreRomano: "IX",
    año: 5,
    creditos: 10,
    area: "practica",
    prerrequisitos: ["Proyecto de Grado"],
    descripcion: "Desarrollo y recopilación empírica del trabajo de memoria o tesis de titulación.",
  },
  {
    id: "practica-profesional",
    nombre: "Práctica Profesional",
    codigo: "PRA-501",
    semestre: 9,
    semestreRomano: "IX",
    año: 5,
    creditos: 16,
    area: "practica",
    idAsignaturaDb: 6,
    prerrequisitos: ["Práctica Pedagógica"],
    descripcion: "Inmersión profesional completa en colegio asignado como docente de matemática en práctica.",
  },

  // ── AÑO 5: SEMESTRE X ──
  {
    id: "electivo-3",
    nombre: "Electivo III",
    codigo: "ELE-501",
    semestre: 10,
    semestreRomano: "X",
    año: 5,
    creditos: 4,
    area: "general",
    descripcion: "Seminario de profundización matemática o educación inclusiva.",
  },
  {
    id: "electivo-4",
    nombre: "Electivo IV",
    codigo: "ELE-502",
    semestre: 10,
    semestreRomano: "X",
    año: 5,
    creditos: 4,
    area: "general",
    descripcion: "Electivo de preparación para la inserción laboral y gestión de proyectos educativos.",
  },
  {
    id: "electivo-5",
    nombre: "Electivo V",
    codigo: "ELE-503",
    semestre: 10,
    semestreRomano: "X",
    año: 5,
    creditos: 4,
    area: "general",
    descripcion: "Electivo libre de especialización pedagógica.",
  },
  {
    id: "electivo-6",
    nombre: "Electivo VI",
    codigo: "ELE-504",
    semestre: 10,
    semestreRomano: "X",
    año: 5,
    creditos: 4,
    area: "general",
    descripcion: "Electivo avanzado de matemática aplicada o didáctica experimental.",
  },
  {
    id: "titulacion-2",
    nombre: "Actividad de Titulación II",
    codigo: "TIT-502",
    semestre: 10,
    semestreRomano: "X",
    año: 5,
    creditos: 12,
    area: "practica",
    prerrequisitos: ["Actividad de Titulación I"],
    descripcion: "Redacción final, presentación y defensa pública del examen de titulación profesional.",
  },
];

// Agrupar asignaturas por año y semestre
export const MALLA_POR_AÑOS: AñoData[] = [
  {
    año: 1,
    titulo: "Año 1",
    semestres: [
      {
        numero: 1,
        romano: "I SEMESTRE",
        año: 1,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 1),
      },
      {
        numero: 2,
        romano: "II SEMESTRE",
        año: 1,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 2),
      },
    ],
  },
  {
    año: 2,
    titulo: "Año 2",
    semestres: [
      {
        numero: 3,
        romano: "III SEMESTRE",
        año: 2,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 3),
      },
      {
        numero: 4,
        romano: "IV SEMESTRE",
        año: 2,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 4),
      },
    ],
  },
  {
    año: 3,
    titulo: "Año 3",
    semestres: [
      {
        numero: 5,
        romano: "V SEMESTRE",
        año: 3,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 5),
      },
      {
        numero: 6,
        romano: "VI SEMESTRE",
        año: 3,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 6),
      },
    ],
  },
  {
    año: 4,
    titulo: "Año 4",
    semestres: [
      {
        numero: 7,
        romano: "VII SEMESTRE",
        año: 4,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 7),
      },
      {
        numero: 8,
        romano: "VIII SEMESTRE",
        año: 4,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 8),
      },
    ],
  },
  {
    año: 5,
    titulo: "Año 5",
    semestres: [
      {
        numero: 9,
        romano: "IX SEMESTRE",
        año: 5,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 9),
      },
      {
        numero: 10,
        romano: "X SEMESTRE",
        año: 5,
        asignaturas: MALLA_ASIGNATURAS.filter((a) => a.semestre === 10),
      },
    ],
  },
];
